services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./docker/images/n8n/Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "saqlain"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "amjad243hq"
			- key: WEBHOOK_URL
        value: "https://n8n-b5ez.onrender.com"
			- key: DB_TYPE
        value: "postgresdb"
      - key: DB_POSTGRESDB_HOST
        value: "dpg-d13u3bi4d50c73ebmngg-a"
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: "n8n_db_p94z"
      - key: DB_POSTGRESDB_USER
        value: "n8n_db_p94z_user"
      - key: DB_POSTGRESDB_PASSWORD
        value: "rBji6E69ABEVo5CHUEUMEB4INtQLl90q"
      
